title: repo-template
author:
  name: ZHENG Robert
  #email: no.spam@hotmail.dev
description: Webserver to check content of a Docker image (GH-Pages)

remote_theme: jekyll/minima
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: auto
  social_links: 
    - { platform: github,         user_url: "https://github.com/Zheng-Bote" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/robert-zheng-67899965/" }
  date_format: "%Y-%m-%d %H:%M"


author:
  name: ZHENG Robert
  #email: no.spam@hotmail.dev

page_created: 2025-02-23
page_url: https://zheng-bote.github.io/web-srv_image-tester
page_desc: Crow webserver to check docker image content

header_pages:
  - about.md
  - links.md
